name: Daily Digest Scheduler

on:
  schedule:
    - cron: "0 8 * * *"  # Every day at 08:00 UTC
  workflow_dispatch:

jobs:
  send-digest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      # Deploy the function
      - run: supabase functions deploy send-digest --project-ref asxslhpisdqkggjargfm --no-verify-jwt
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      # Invoke function via HTTPS POST
      - name: Invoke send-digest
        run: |
          curl -X POST https://asxslhpisdqkggjargfm.functions.supabase.co/send-digest
